version: '3.5'

services:
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./app:/var/www/app
        environment:
            APP_ENV: ${APP_ENV}

    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./app:/var/www/app
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        environment:
            APP_ENV: ${APP_ENV}
        ports:
            - 80:80


